### ISSUE TITLE
Pause event aggregator when scene loads / unloads

### ISSUE THREAD

**Issue by joemicmc** [8bitape/UniRxEventAggregator#4]
When working on https://github.com/8bitape/GlobalGameJam2019 we found that reloading scene throws errors as some events were still firing with destroyed objects.

Would be nice to have some way of pausing the event aggregator when a scene is loading / unloading.

**Comment by cargowire** [comment]
If I pull that project can I repeat the issue? Pause feels like the wrong way - how long would you pause for? do we think the destroying of game objects in a scene is instant or has a delay?

**Comment by joemicmc** [comment]
Destroy doesn't happen straight away, but will happen sometime in same frame. I'll add a branch with a reproduction of issue! With took a different approach to achieve same behaviour in game jam.

From docs:

> Actual object destruction is always delayed until after the current Update loop, but will always be done before rendering.

**Comment by joemicmc** [comment]
(Maybe pause until end of frame?)

**Comment by joemicmc** [comment]
The more I think about this, the more I think it's an implementation problem. I need to add some kind of Unity framework thing that validates properties.

**Comment by joemicmc** [comment]
I've created a pull request for a custom attribute in a new repo: https://github.com/8bitape/UnityFramework/pull/1

Example of usage:

    public class PrintGameObjectName : MonoBehaviour
    {
        [SerializeField]
        private GameObject _gameObject = null;

        [RequiredProperty]
        private GameObject GameObject { get { return this._gameObject; } }

        private void Update()
        {
            if (!this.IsValidObject())
            {
                Debug.Log("There are properties with null values!");
            }
            else
            {
                Debug.Log(this.GameObject.name);
            }
        }
    }
